channels:
  - defaults
  - conda-forge
dependencies:
  - pip=19.0.1
  - python=3.6
  - cartopy
  - jupyter
  - matplotlib
  - netcdf4
  - tqdm
  - xarray
  - dask
  - bottleneck
  - pystan
  - dask-image>=0.5.0
  - scipy
  - matplotlib
  - seaborn
  - scikit-image
  - ipdb
  - luigi
  - jupyter
  - notebook
  - numba
  - pip:
    - hues
